# Generated by Django 4.1.7 on 2023-04-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfeid', models.IntegerField()),
                ('access_key', models.CharField(max_length=50)),
                ('purchase_date', models.DateTimeField()),
                ('place_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('product_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('qtty', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('gross_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('total_tax_value', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('liquid_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('aditional_info', models.TextField(blank=True, null=True)),
                ('gtin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ncm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('calc_rule', models.CharField(blank=True, max_length=1, null=True)),
                ('icms_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pis_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pis_st_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('cofins_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('confins_st_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('issqn_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cfe.header')),
            ],
        ),
    ]
