# Generated by Django 4.1.7 on 2023-04-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfeid', models.IntegerField()),
                ('access_key', models.CharField(max_length=50)),
                ('purchase_date', models.DateTimeField()),
                ('place_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('product_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('qtty', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_adjustment', models.CharField(max_length=20, null=True)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cfe.header')),
            ],
        ),
    ]
