# Generated by Django 4.1.7 on 2023-03-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='adjustment_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_adjustment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
