# Generated by Django 4.1.7 on 2023-03-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0002_alter_item_adjustment_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='adjustment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
