# Generated by Django 4.1.7 on 2023-06-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
